### ISSUE TITLE
Sparse files not handled correctly

### ISSUE THREAD

**Issue by rexxnor** [stepping-stone/online-backup#4]
A backup of a CentOS 7 machine fails while copying the file "/var/log/lastlog".
Quick workaroud is to add this file to the "OnlineBackupExcludeFiles.conf".

As this file contains information about the people that were logged in last, it is crucial to be included into the backup.

**Comment by Toasterson** [comment]
The Lastlog file is a specialy nasty on RedHat Systems as mutiple bug reports on Redhat Suggest. The official Suggestion is to not Backup the File as Auth information can also be monitored by syslog. Also as Rsync seems to be able to handle a newly created file lastlog nicely. As -S is a good to use option for rsync anyway it has been added. Also lastlog should be excluded by default.
